spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_workplace
    username: sw_user
    password: sw_pass
  task:
    scheduling:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update   # DEV only
    show-sql: true
    properties:
      hibernate:
        format_sql: true
