spring:
  datasource:
#    url: jdbc:postgresql://shortline.proxy.rlwy.net:38052/railway
#    username: postgres
#    password: XWvkGmohKWgQkpsyBqUsZrvSYEgMulFf
      url: jdbc:postgresql://localhost:5432/smart_workplace
      username: admin
      password: admin
      driver-class-name: org.postgresql.Driver

  task:
    scheduling:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sts.windows.net/f54f468f-415b-4a86-a7cf-c9495812c590/


logging:
  level:
    org.example: INFO
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always


meal-booking:
  cutoff-time: "22:00"
  lunch:
    start-time: "12:00"
    end-time: "15:00"
    check-interval-minutes: 30
    geofence-radius-meters: 500



office:
  latitude: 18.560593520927615
  longitude: 73.91641135291994
  radius-meters: 500

azure:
  tenant-id: f54f468f-415b-4a86-a7cf-c9495812c590
  client-id: 12b1e09e-023f-430b-bf15-13d1223afb90