spring:
  datasource:
    url: postgresql://postgres:XWvkGmohKWgQkpsyBqUsZrvSYEgMulFf@postgres.railway.internal:5432/railway
    username: postgres
    password: XWvkGmohKWgQkpsyBqUsZrvSYEgMulFf

  task:
    scheduling:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update   # DEV only
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public

office:
  latitude: 18.5204
  longitude: 73.8567
  radius-meters: 500
