spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: XWvkGmohKWgQkpsyBqUsZrvSYEgMulFf
    driver-class-name: org.postgresql.Driver


  task:
    scheduling:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update   # DEV only
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public

office:
  latitude: 18.5204
  longitude: 73.8567
  radius-meters: 500
